### ISSUE TITLE
Add population pyramid

### ISSUE THREAD

**Issue by BruceHenry** [BruceHenry/WorldPopulationData#3]
Add a population pyramid to each country.
<img src="http://www.geo.hunter.cuny.edu/tbw/ncc/Notes/Chapter6.pop/Chapter6.pop/pop.structure.developing.2002.jpg" width="300" height="300" />
(This feature is beyond the proposal and may not be implemented.)

**Comment by anqi-lu** [comment]
Looks cool! How would this pyramid be displayed in the map if implemented? Hover by country?

**Comment by BruceHenry** [comment]
@anqi-lu I plan to display it in the left-bottom of the map, so that you can change the year to see its changing over time.

**Comment by Q-Zhao** [comment]
This is cool! My project has a similar issue to interactively select a country : https://github.com/Q-Zhao/dataviz-project-QZhao/issues/3

**Comment by ZijunXu** [comment]
Looks awesome, great design. It inspires me a lot.
