### ISSUE TITLE
Comma Format in Bars

### ISSUE THREAD

**Issue by curran** [BruceHenry/WorldPopulationData#5]
This project looks amazing!

![image](https://user-images.githubusercontent.com/68416/31849910-01d430ec-b668-11e7-9fd1-e58f7b820e85.png)

It might be a nice touch to add a comma formatter for the bars, and their `<title>` tooltips.

**Comment by BruceHenry** [comment]
@curran The comma has been added.

**Comment by curran** [comment]
Nice!
